
version: "3.9"
services:
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      HOST: 0.0.0.0
    depends_on:
      - cache
      - db
      - zk
  cache:
    image: "redis:alpine"
    ports:
      - 6379:6379
  zk:
    image: "zookeeper"
    ports:
      - 2181:2181

  db:
    image: "dajobe/hbase"
    ports:
      - 32872:32872




  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic


  logstash:
    image: "logstash:7.12.0"
    ports:
      - 9500:9500
      - 9200:9200
    command: logstash -f /config-dir/logstash.conf
    volumes:
      - ./:/config-dir
    depends_on:
      - elasticsearch
      - kibana

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.12.0"
    ports:
      - 5601:5601
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'


volumes:
  data01:
    driver: local


networks:
  elastic:
    driver: bridge
