
version: "3.9"
services:
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      HOST: 0.0.0.0
    depends_on:
      - cache
      - db
      - zk
    networks:
      - elastic

  cache:
    image: "redis:alpine"
    ports:
      - 6379:6379

    networks:
        - elastic

  zk:
    image: "zookeeper"
    ports:
      - 2181:2181
    networks:
        - elastic

  db:
    image: "dajobe/hbase"
    ports:
      - 32872:32872
    networks:
      - elastic



#  es01:
#      image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
#      container_name: es01
#      environment:
#        - discovery.type=single-node
#        - bootstrap.memory_lock=true
#        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      ulimits:
#        memlock:
#          soft: -1
#          hard: -1
#      volumes:
#        - data01:/usr/share/elasticsearch/data
#      ports:
#        - 9200:9200
#      networks:
#        - elastic
#  logstash:
#    image: "logstash:7.12.0"
#    ports:
#      - 9500:9500
#    command: logstash -f /config-dir/logstash.conf
#    volumes:
#      - ./:/config-dir
#    depends_on:
#      - es01
#      - kibana
#    networks:
#      - elastic

#  kibana:
#    image: "docker.elastic.co/kibana/kibana:7.12.0"
#    ports:
#      - 5601:5601
#    environment:
#      SERVER_NAME: kibana
#      ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
#    networks:
#      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local


networks:
  elastic:
    driver: bridge
